param(
    [string]$InputPath = "Dump/UHTHeaderDump/Pal/Public/EPalWazaID.h",
    [string]$OutputPath = "mods/PalworldEditor/inc/skills/active_skill_definitions.hpp"
)

$resolvedInput = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\$InputPath"))
$resolvedOutput = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\$OutputPath"))
$entries = [Collections.Generic.List[object]]::new()
$nextValue = 0

foreach ($line in [IO.File]::ReadAllLines($resolvedInput)) {
    if ($line -notmatch '^\s*([A-Za-z_][A-Za-z0-9_]*)(?:\s*=\s*(\d+))?,\s*$') {
        continue
    }

    $name = $Matches[1]
    if ($Matches[2]) {
        $nextValue = [int]$Matches[2]
    }
    if ($nextValue -gt [uint16]::MaxValue) {
        throw "EPalWazaID value $nextValue for $name exceeds uint16"
    }
    if ($name -notin @("None", "MAX")) {
        $entries.Add([pscustomobject]@{ Name = $name; Value = $nextValue })
    }
    ++$nextValue
}

if ($entries.Count -eq 0) {
    throw "No EPalWazaID entries were parsed from $resolvedInput"
}
if (($entries.Value | Sort-Object -Unique).Count -ne $entries.Count) {
    throw "EPalWazaID contains duplicate non-sentinel numeric values"
}
if (($entries.Name | Sort-Object -Unique).Count -ne $entries.Count) {
    throw "EPalWazaID contains duplicate non-sentinel names"
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add("/**")
$lines.Add(" * @file active_skill_definitions.hpp")
$lines.Add(" * @brief Generated Palworld 1.0 active-skill values and Raw IDs.")
$lines.Add(" * @note Generated by scripts/generate-active-skill-definitions.ps1 from")
$lines.Add(" *       Dump/UHTHeaderDump/Pal/Public/EPalWazaID.h; do not edit manually.")
$lines.Add(" */")
$lines.Add("#pragma once")
$lines.Add("")
$lines.Add("#include <array>")
$lines.Add("#include <cstdint>")
$lines.Add("#include <optional>")
$lines.Add("#include <span>")
$lines.Add("#include <string>")
$lines.Add("#include <string_view>")
$lines.Add("")
$lines.Add("namespace skill_editor {")
$lines.Add("struct ActiveSkillDefinition {")
$lines.Add("    std::uint16_t value;")
$lines.Add("    std::string_view id;")
$lines.Add("};")
$lines.Add("")
$lines.Add("inline constexpr std::array kActiveSkillDefinitions{")
foreach ($entry in $entries) {
    $lines.Add(
        "    ActiveSkillDefinition{.value = $($entry.Value), .id = `"$($entry.Name)`"},")
}
$lines.Add("};")
$lines.Add("")
$lines.Add("[[nodiscard]] constexpr auto active_skill_definitions() noexcept")
$lines.Add("    -> std::span<const ActiveSkillDefinition> {")
$lines.Add("    return kActiveSkillDefinitions;")
$lines.Add("}")
$lines.Add("")
$lines.Add("[[nodiscard]] constexpr auto find_active_skill_id(const std::uint16_t value) noexcept")
$lines.Add("    -> std::optional<std::string_view> {")
$lines.Add("    for (const auto& definition : kActiveSkillDefinitions) {")
$lines.Add("        if (definition.value == value) {")
$lines.Add("            return definition.id;")
$lines.Add("        }")
$lines.Add("    }")
$lines.Add("    return std::nullopt;")
$lines.Add("}")
$lines.Add("")
$lines.Add("[[nodiscard]] inline auto active_skill_id_or_numeric(const std::uint16_t value) -> std::string {")
$lines.Add("    if (const auto id = find_active_skill_id(value)) {")
$lines.Add("        return std::string(*id);")
$lines.Add("    }")
$lines.Add("    return std::to_string(value);")
$lines.Add("}")
$lines.Add("}  // namespace skill_editor")

$utf8WithoutBom = [Text.UTF8Encoding]::new($false)
[IO.File]::WriteAllText($resolvedOutput, [string]::Join("`n", $lines) + "`n", $utf8WithoutBom)
Write-Host "Generated $($entries.Count) active skills at $resolvedOutput"
